ecomapp/urls.py
from django.urls import path
from .views import *

app_name="ecomapp"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact-us/', ContactView.as_view(), name='contact'),
    path('all-products/', AllProductView.as_view(), name="allproducts"),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name="productdetail"),
    path('add-to-cart<int:pro_id>/', AddToCartView.as_view(), name="addtocart"),
    path('my-cart/', MyCartView.as_view(), name="mycart"),
    path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name="managecart"),
    path('empty-cart/', EmptyCartView.as_view(), name="emptycart"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('register/', CustomerRegistrationView.as_view(), name="customerregistration"),
    path('logout/', CustomerLogoutView.as_view(), name="customerlogout"),
    path('login/', CustomerLoginView.as_view(), name="customerlogin"),
    path('search/', SearchView.as_view(), name="search"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.title
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: "+str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: "+ str(self.id) + "CartProduct: "+ str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing","Order Processing"),
    ("On the Way", "On the Way"),
    ("Order Completed", "Order Completed"),
    ("Order Cancelled", "Order Cancelled"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField(null=True)
    discount = models.PositiveIntegerField(null=True)
    total = models.PositiveIntegerField(null=True)
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>Best Ecommerce site in the world</h1>
{% endblock %}

templates/addtocart.html
{% extends 'base.html' %}
{% block title %}Add to cart{% endblock %}
{% block content %}
<div class="container">
    <h3>Product added to cart succesfully</h3>
</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}
{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <h1>All Products</h1>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-4">
            <div class="m-4">
                <a href="{% url 'ecomapp:productdetail' p.slug%}"><h3>{{p.title}}</h3></a>
                <img src="{{p.image.url}}" alt=""  class="img-fluid" style="height: 2500; object-fit:cover;">
                <p>Price: <strike>{{p.marked_price}}$</strike> {{p.selling_price}}$</p>
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add to cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <a href="{% url 'ecomapp:home' %}">Home| </a>
    <a href="{% url 'ecomapp:about' %}">About Us| </a>
    <a href="{% url 'ecomapp:contact' %}">Contact Us| </a>
    <a href="{% url 'ecomapp:allproducts' %}">All Products| </a>
    <a href="{% url 'ecomapp:mycart' %}">My Cart| </a>
    {% if request.user.customer %}
    Welcome {{request.user.username}}
    <a href="{% url 'ecomapp:customerlogout' %}">Logout| </a> 
    {% else %}
    <a href="{% url 'ecomapp:customerregistration' %}">Register| </a>
    <a href="{% url 'ecomapp:customerlogin' %}">Login| </a>
    {% endif %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <form action="{% url 'ecomapp:search' %}" method="get">
                    <input type="text" name="keyword" placeholder="Search product here..." required>
                    <button>Search</button>
                </form>
            </div>
        </div>
    </div>
    {% block content %}

    <h1>Welcome Ecommer</h1>
    {% endblock %}
</body>
</html>

templates/checkout.html
{% extends 'base.html' %}
{% block title %} Checkout {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items In Cart</h3>
            <a href="{% url 'ecomapp:mycart' %}" class="btn btn-info">Back to cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>{{cart.total}}</th>
                    </tr>
                </tbody>
            </table>  
        </div>
        <div class="col-md-6">
            <h3>Checkout form</h3>
            {% csrf_token %}
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Place Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block content %}
    <h1>Call the folowing number</h1>
    <p>08128307234</p>
{% endblock %}

templates/customerlogin.html
{% extends 'base.html' %}
{% block title %}Customer Login{% endblock %}
{% block content %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Login</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login</button>
                {% if error %}
                <li>{{error}}</li>
                {% endif %}
            </form>
            <p>Or don't have an account? <a href="{% url 'ecomapp:customerregistration'%}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}" class="btn btn-info">Register here</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}
{% block title %}Customer Registration{% endblock %}
{% block content %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register as Customer</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Welcome Ecommer</h1>
    <hr>
    <div class="container">
        <div class="row mt-3">
            {% for p in product_list %}
            <div class="col-md-4">
                <div class="m-4">
                    <a href="{% url 'ecomapp:productdetail' p.slug%}"><h3>{{p.title}}</h3></a>
                    <img src="{{p.image.url}}" alt=""  class="img-fluid" style="height: 2500; object-fit:cover;">
                    <p>Price: <strike>{{p.marked_price}}$</strike> {{p.selling_price}}$</p>
                    <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add to cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    
{% endblock %}

templates/mycart.html
{% extends 'base.html' %}
{% block title %} My Cart {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4">Total</th>
                        <th>{{cart.total}}</th>
                        {% if cart.cartproduct_set %}
                        <th><a href="{% url 'ecomapp:emptycart' %}">Empty cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'ecomapp:checkout' %}">Checkout</a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/productdetail.html
{% extends 'base.html' %}
{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>{{product.title}}</h3>
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image.url}}" alt="" srcset="" class="img-fluid" width="1000px">
        </div>

        <div class="col-md-6">
            <h4>{{product.title}}</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: <strike>{{product.marked_price}}$</strike> {{product.selling_price}}</h5>
            <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-info">Add to Cart</a>
            <hr>
            <p>Warranty: {{product.warranty}}</p>
            <p>{{product.description}}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block title %}Search{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for "{{request.GET.keyword}}"</h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-4">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-8">
                    <h4><a href="{% url 'ecomapp:productdetail' result.slug%}">{{result.title}}</a></h4>
                    <p>{{result.description | truncatewords:50}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}